# fly.toml app configuration file generated for housing-support-stack on 2024-06-27T18:16:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'housing-support-stack'
primary_region = 'lax'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION="sqlite"
  DB_DATABASE="/var/www/html/storage/database/database.sqlite"
  CACHE_STORE="file"
  APP_NAME="housing-support-stack"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="storage_vol"
  destination="/var/www/html/storage"

[processes]
  app = ""
  cron = "cron -f"
  worker = "php artisan queue:listen"